on:
  push:
    branches:
      - main

jobs:
  deploy-hugo:
    name: Deploy Hugo Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-deploy-hugo
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-bucket-name: ericcbonet-blog-frontend
          deploy: true
          domain-name: ericcbonet.com
